// Code generated by goctl. DO NOT EDIT!
// Source: role.proto

package role

import (
	"context"

	"Ningxi-Compose/usermanage/rpc/types/client"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Response    = role.Response
	RoleRequest = role.RoleRequest

	Role interface {
		Create(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

func (m *defaultRole) Create(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := role.NewRoleClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}
