// Code generated by goctl. DO NOT EDIT!
// Source: role.proto

package server

import (
	"context"

	"Ningxi-Compose/usermanage/rpc/internal/logic"
	"Ningxi-Compose/usermanage/rpc/internal/svc"
	"Ningxi-Compose/usermanage/rpc/types/role"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	role.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServer) Create(ctx context.Context, in *role.RoleRequest) (*role.Response, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}
