// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"Ningxi-Compose/usermanage/rpc/internal/logic"
	"Ningxi-Compose/usermanage/rpc/internal/svc"
	"Ningxi-Compose/usermanage/rpc/types/client"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	client.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *client.LoginRequest) (*client.Response, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *client.RegisterRequest) (*client.Response, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Userinfo(ctx context.Context, in *client.UserinfoRequest) (*client.Response, error) {
	l := logic.NewUserinfoLogic(ctx, s.svcCtx)
	return l.Userinfo(in)
}
